name: CI
on:
  push:

jobs:
  build_apk:
    name: Build flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '8.x' #https://github.com/subosito/flutter-action/issues/58
    - name: Setup subosito/flutter-action@v1
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20'
    - name: Clean workspace
      run: flutter clean
    - name: Install NDK (workaround to https://github.com/gradle/gradle/issues/12440)
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
    - name: create env file
      run: |
        touch assets/.env
        echo "APPCENTER_BUILD_ID=${{ secrets.APPCENTER_BUILD_ID }}" > assets/.env
        echo "APPCENTER_KEYSTORE_PASSWORD=${{ secrets.APPCENTER_KEYSTORE_PASSWORD }}" >> assets/.env
        echo "APPCENTER_KEY_ALIAS=${{ secrets.APPCENTER_KEY_ALIAS }}" >> assets/.env
        echo "APPCENTER_KEY_PASSWORD=${{ secrets.APPCENTER_KEY_PASSWORD }}" >> assets/.env
        echo "MNENOMIC=${{ secrets.MNENOMIC }}" >> assets/.env
        echo "ETHEREUM_ADDRESS=${{ secrets.ETHEREUM_ADDRESS }}" >> assets/.env
        echo "CONTRACT_ADDRESS_LOCKDROP_TESTNET=${{ secrets.CONTRACT_ADDRESS_LOCKDROP_TESTNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_MXC_TESTNET=${{ secrets.CONTRACT_ADDRESS_MXC_TESTNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_IOTA_PEGGED_TESTNET=${{ secrets.CONTRACT_ADDRESS_IOTA_PEGGED_TESTNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_LOCKDROP_MAINNET=${{ secrets.CONTRACT_ADDRESS_LOCKDROP_MAINNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_MXC_MAINNET=${{ secrets.CONTRACT_ADDRESS_MXC_MAINNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_IOTA_PEGGED_MAINNET=${{ secrets.CONTRACT_ADDRESS_IOTA_PEGGED_MAINNET }}" >> assets/.env
        echo "INFURA_API_PROJECT_ID=${{ secrets.INFURA_API_PROJECT_ID }}" >> assets/.env
        echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> assets/.env
    - name: Build APK
      run: flutter build apk --flavor prod
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/flutter-apk
        
  build_ios:
    name: Build flutter (IOS)
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '8.x' #https://github.com/subosito/flutter-action/issues/58
    - name: Setup subosito/flutter-action@v1
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20'
    - name: Clean workspace
      run: flutter clean
    - name: create env file
      run: |
        touch assets/.env
        echo "APPCENTER_BUILD_ID=${{ secrets.APPCENTER_BUILD_ID }}" > assets/.env
        echo "APPCENTER_KEYSTORE_PASSWORD=${{ secrets.APPCENTER_KEYSTORE_PASSWORD }}" >> assets/.env
        echo "APPCENTER_KEY_ALIAS=${{ secrets.APPCENTER_KEY_ALIAS }}" >> assets/.env
        echo "APPCENTER_KEY_PASSWORD=${{ secrets.APPCENTER_KEY_PASSWORD }}" >> assets/.env
        echo "MNENOMIC=${{ secrets.MNENOMIC }}" >> assets/.env
        echo "ETHEREUM_ADDRESS=${{ secrets.ETHEREUM_ADDRESS }}" >> assets/.env
        echo "CONTRACT_ADDRESS_LOCKDROP_TESTNET=${{ secrets.CONTRACT_ADDRESS_LOCKDROP_TESTNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_MXC_TESTNET=${{ secrets.CONTRACT_ADDRESS_MXC_TESTNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_IOTA_PEGGED_TESTNET=${{ secrets.CONTRACT_ADDRESS_IOTA_PEGGED_TESTNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_LOCKDROP_MAINNET=${{ secrets.CONTRACT_ADDRESS_LOCKDROP_MAINNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_MXC_MAINNET=${{ secrets.CONTRACT_ADDRESS_MXC_MAINNET }}" >> assets/.env
        echo "CONTRACT_ADDRESS_IOTA_PEGGED_MAINNET=${{ secrets.CONTRACT_ADDRESS_IOTA_PEGGED_MAINNET }}" >> assets/.env
        echo "INFURA_API_PROJECT_ID=${{ secrets.INFURA_API_PROJECT_ID }}" >> assets/.env
        echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> assets/.env
    - name: Build IOS
      run: flutter build ios --release --no-codesign
    - name: Upload IPA
      uses: actions/upload-artifact@master
      with:
        name: ios-build
        path: build/ios/iphoneos
